/**
 * Definitions
 * 
 * This file contains all the definitions for the application.
 * 
 */
export const APP_NAME = process.env.APP_NAME || 'Next.js'
export const APP_DESCRIPTION = process.env.APP_DESCRIPTION || 'Generated by Next.js'
export const APP_URL = process.env.APP_URL || 'http://localhost:3000'
export const API_URL = process.env.API_URL || 'http://127.0.0.1:1337/api'
export const API_PUBLIC_URL = process.env.API_PUBLIC_URL || 'http://127.0.0.1:1337/'